package:
  name: protobuf
  version: 2.6.1

source:
  git_url: https://github.com/google/protobuf.git
  git_tag: v2.6.1

about:
  home: https://developers.google.com/protocol-buffers/
  summary: 'Protocol buffers are a language-neutral, platform-neutral extensible mechanism for serializing structured data'
